services:
  backend:
    build: ./backend
    container_name: sayonph-backend-service
    ports:
      - "5001:5000"  # local:container
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://db_sayonph:sayonph19!@cluster0.zjjwqmv.mongodb.net/sayonph

  frontend:
    build: ./frontend
    container_name: sayonph-frontend-service
    ports:
      - "8001:80" # local:container
    depends_on:
      - backend
